version: '3.7'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        volumes:
            - ./store_files:/store_files_postgresql/
        logging:
            options:
                max-size: 10m
                max-file: "3"



    webserver:
        image: puckel/docker-airflow:1.10.9
#        build:
#            context: https://github.com/puckel/docker-airflow.git#1.10.9
#            dockerfile: Dockerfile
#            args:
#                PYTHON_DEPS: pymongo==4.1.0
        restart: always
        depends_on:
            - postgres
#            - mysql
        environment:
            - INSTALL_MYSQL=y
            - LOAD_EX=n
            - EXECUTOR=Local
            - AIRFLOW__SMTP__SMTP_HOST=smtp.gmail.com
            - AIRFLOW__SMTP__SMTP_USER=example@gmail.com
            - AIRFLOW__SMTP__SMTP_PASSWORD=hdwiondmyyobhlto
            - AIRFLOW__SMTP__SMTP_PORT=587
            - AIRFLOW__SMTP__SMTP_MAIL_FROM=Airflow
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./store_files:/usr/local/airflow/store_files_airflow
            - ./sql_files:/usr/local/airflow/sql_files
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8081:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
    redis:
               image: 'redis:3.2.7'
# network interfaces
#networks:
#    port: 27017
#    bindIp: 127.0.0.1,172.17.0.1
